common:
  app: fdkoracle
  shortname: fdkoracle
  team: sd
  env: dev
  container:
    cpu: 200m
    image: <+artifacts.primary.image>
    memory: 512
    replicas: 1
    maxReplicas: 2
    probes:
      liveness:
        path: /health/alive
      readiness:
        path: /health/ready
  ingress:
    enabled: true
    trafficType: public
    host: fdk-llm.dev.entur.io
  deployment:
    enabled: true
  service:
    enabled: true
